[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  # Timeout should be specified per function
  "get-quote" = { timeout = 10 }  # Specific function timeout

[dev]
  framework = "#static"
  targetPort = 3000
  publish = "dist"