[build]
  command = "npm install && npm run build"  # Keep your build command
  functions = "netlify/functions"
  publish = "."  # Root directory publishing

[functions]
  node_bundler = "esbuild"
  "get-quote" = { timeout = 10 }  # Specific timeout for your function

[dev]
  framework = "#static"
  targetPort = 3000
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200